# Generated by Django 5.2 on 2025-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("12th_pass", "12th Pass"),
                            ("graduate", "Graduate"),
                            ("parent", "Parent"),
                            ("nri", "NRI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("neet_rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
