# Generated by Django 5.2 on 2025-04-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="tambnail_url",
            field=models.TextField(blank=True),
        ),
    ]
