# Generated by Django 5.2 on 2025-05-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_university_tambnail_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="banner_image_url",
        ),
        migrations.RemoveField(
            model_name="university",
            name="brochure_url",
        ),
        migrations.RemoveField(
            model_name="university",
            name="logo_image_url",
        ),
        migrations.RemoveField(
            model_name="university",
            name="tambnail_url",
        ),
        migrations.AddField(
            model_name="university",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="university",
            name="brochure",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
        migrations.AddField(
            model_name="university",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="university",
            name="tambnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="tambnails/"),
        ),
    ]
