# Generated by Django 5.2 on 2025-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_remove_university_banner_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.TextField(),
        ),
    ]
