# Generated by Django 5.2 on 2025-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0004_alter_university_location_alter_university_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="highlights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
