# Generated by Django 5.2 on 2025-05-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0005_university_highlights"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="applygrad_rankings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("course_type", models.CharField(default="Full Time", max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("UG", "Undergraduate"),
                            ("PG", "Postgraduate"),
                            ("Doctoral", "Doctoral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certificate_program", models.BooleanField(default=False)),
                ("duration", models.CharField(max_length=50)),
                ("total_fees", models.CharField(max_length=50)),
                ("seats", models.PositiveIntegerField()),
                ("exams", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="university.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniversityPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("pg", "PG"), ("ug", "UG")], max_length=50
                    ),
                ),
                ("year_span", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("about", models.TextField()),
                ("key_highlights", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="university.university",
                    ),
                ),
            ],
        ),
    ]
