# Generated by Django 5.2 on 2025-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0006_university_applygrad_rankings_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="map_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
