# Generated by Django 5.2 on 2025-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0007_university_map_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="map_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
