# Generated by Django 5.2 on 2025-06-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0008_alter_university_map_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("application_start_date", models.DateField(blank=True, null=True)),
                ("application_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="exams",
        ),
        migrations.AddField(
            model_name="course",
            name="exams",
            field=models.ManyToManyField(related_name="courses", to="university.exam"),
        ),
    ]
