# Generated by Django 5.2 on 2025-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0009_exam_remove_course_exams_course_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="exams",
            field=models.ManyToManyField(
                related_name="university", to="university.exam"
            ),
        ),
    ]
