# Generated by Django 5.2 on 2025-06-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0010_university_exams"),
    ]

    operations = [
        migrations.CreateModel(
            name="counsellingPrograms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("NEET PG", "NEET PG"), ("NEET UG", "NEET UG")],
                        max_length=255,
                    ),
                ),
                ("program", models.CharField(max_length=1000, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="counsellingTimelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("round_number", models.CharField(max_length=100)),
                ("stage", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelines",
                        to="university.counsellingprograms",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "date"],
            },
        ),
    ]
